src/components/modals/modal-congrats-number/index.tsx
src/components/modals/modal-congrats-number/modal-congrats.module.scss
src/components/number-wheel/index.tsx
src/components/number-wheel/number-wheel-top/index.tsx
src/components/number-wheel/rotation/index.tsx
src/components/number-wheel/type.ts
src/components/option/hide-button.tsx
src/components/option/index.tsx
src/components/option/input.tsx
src/components/option/setting-button.tsx
src/components/patials/footer/footer-left/index.tsx
src/components/patials/footer/index.tsx
src/components/patials/header/drawer-navbar/index.tsx
src/components/patials/header/header-left/index.tsx
src/components/patials/header/header-right/index.tsx
src/components/patials/header/index.tsx
src/components/random-number/index.tsx
src/hooks/use-random-number.ts
tailwind.config.js

[PON-22] Responsive về tablet

---

src/components/number-wheel/index.tsx
src/components/option/setting-button.tsx
src/components/random-number/index.tsx
src/core-ui/modal/modal.tsx
src/hooks/use-random-number.ts

[PON-23] Sửa lỗi không hiện popup chúc mừng khi ở chế độ toàn màn hình

---

src/components/modals/modal-congrats-number/index.tsx
src/components/number-wheel/index.tsx
src/components/number-wheel/rotation/index.tsx
src/components/option/input.tsx
src/components/option/setting-button.tsx
src/components/patials/header/drawer-navbar/index.tsx
src/components/random-number/index.tsx
tailwind.config.js

[PON-25] Chỉnh sửa lại UI 1 số chỗ

---

src/components/number-wheel/index.tsx
src/components/timer/index.tsx
src/hooks/use-timer.ts

[PON-26] Hiển thị thời gian hiện tại

---

src/components/option/hide-button.tsx
src/components/random-number/index.tsx
src/hooks/use-setting.ts

Xử lý thao tác ẩn trong Option

---

src/components/patials/header/drawer-navbar/index.tsx
src/components/random-number/index.tsx

[Pon 27] Sửa lỗi UI thời gian bị tràn khi responsive

---

src/components/option/default-number/default-number-button.tsx
src/components/option/input.tsx
src/components/patials/footer/footer-left/index.tsx

[PON-28] Không cho người dùng thay đổi giá trị sau khi bấm quay

---

src/components/lucky-wheel/spinner-board/index.tsx
src/components/lucky-wheel/spinner-indicator/index.tsx
src/components/lucky-wheel/spinner-indicator/style.module.scss
src/components/lucky-wheel/spinner-trigger/style.module.scss
src/components/lucky-wheel/style.module.scss
src/components/lucky-wheel/utils/contanst.ts
src/components/lucky-wheel/utils/index.ts
src/components/random-wheel/wheel/index.tsx

[PON-42] Change Random Wheel color

---

package.json
src/components/common/random-main/random-main-top/index.tsx
src/components/number-wheel/index.tsx
src/components/number-wheel/rotation/index.tsx
src/components/option/setting-random/index.tsx
src/components/option/setting-random/input.tsx
src/components/option/setting-random/setting-form.tsx
src/hooks/use-setting.ts
yarn.lock

Thêm chức năng custom màu nền trong setting

---

public/robots.txt
src/components/common/random-main/random-main-top/index.tsx
src/components/number-wheel/index.tsx
src/components/number-wheel/rotation/index.tsx
src/components/option/setting-random/custom-setting-form.tsx
src/components/option/setting-random/setting-form.tsx
src/hooks/use-setting.ts

Fix vị trí của bảng màu

---

src/api/axios-client.ts

[PON-57] Add .env NEXT_PUBLIC_API_URL

---

src/components/login-page/index.tsx
src/components/login-page/login-form/index.tsx

Responsive login page

---

src/components/login-page/login-form/index.tsx

Fix responsive mobile

---

src/components/login-page/login-form/index.tsx
src/components/login-page/login-welcom/index.tsx
src/core-ui/eclipse/index.tsx

Hoàn chỉnh UI trang Đăng Nhập
PC/Laptop screen
IPad screen
Mobile screen

Hoàn chỉnh UI trang Đăng Nhập

---

src/components/common/auth-page/auth-welcome/auth-button/index.tsx
src/components/common/auth-page/auth-welcome/index.tsx
src/components/login-page/login-form/index.tsx
src/components/signup-page/index.tsx
src/components/signup-page/signup-form/index.tsx
src/components/signup-page/signup-form/input.tsx
src/hooks/use-public.ts
src/pages/signup/index.tsx

UI Signup Page
PC/Laptop screen
Ipad screen
Mobile screen

UI Signup Page

---

src/components/login-page/login-form/index.tsx
src/components/signup-page/signup-form/index.tsx

Change placeholder in authentication page

Change placeholder in authentication page

---

public/robots.txt
public/sitemap-0.xml
src/common/hooks/use-global.ts
src/common/hooks/use-setting.ts
src/components/common/constant/wheelColor.constant.ts
src/components/common/random-main/index.tsx
src/components/common/random-main/random-main-top/index.tsx
src/components/number-wheel/index.tsx
src/components/number-wheel/rotation/index.tsx
src/components/option/hide-button.tsx
src/components/option/setting-random/custom-setting-form.tsx
src/components/option/setting-random/input.tsx
src/components/option/setting-random/setting-form.tsx
src/components/timer/index.tsx
src/core-ui/icon/index.tsx

Add custom text color in Setting

Add custom text color in Setting

---

src/components/number-wheel/index.tsx
src/components/number-wheel/rotation/index.tsx
src/components/random-number/index.tsx
src/components/random-wheel/index.tsx
tailwind.config.js

[PON-73] Fix number box when insert image or color

---

src/common/constants/setting.constant.ts
src/common/hooks/use-setting.ts
src/components/common/random-main/random-main-top/index.tsx
src/components/number-wheel/index.tsx
src/components/option/hide-button.tsx
src/components/option/setting-random/custom-setting-form.tsx
src/components/option/setting-random/index.tsx
src/components/option/setting-random/input.tsx
src/components/option/setting-random/setting-form.tsx
src/components/random-number/index.tsx
src/components/timer/index.tsx
src/core-ui/color-picker/index.tsx
tailwind.config.js

- MOBILE
- TABLET
- LAPTOP
- PC

[PON-74] Fix responsive setting

---

src/components/common/random-main/index.tsx
src/components/common/random-main/random-main-top/index.tsx
src/components/timer/index.tsx

[PON-75] Fix background layer

---

src/components/common/auth-page/auth-welcome/auth-button/index.tsx
src/components/login-page/login-form/index.tsx
src/components/signup-page/signup-form/index.tsx
src/pages/signup/index.tsx

[PON-76] Fix break layout login, register page

---

src/common/hooks/use-setting.ts
src/components/modals/modal-congrats-number/index.tsx
src/core-ui/button/index.tsx

Change color text and button in CongratsNumber

Change color text and button in CongratsNumber

---

src/components/common/auth-page/auth-welcome/index.tsx

Fix eclipse in authentication welcome

---

src/components/option/index.tsx
src/components/option/input.tsx
src/components/option/setting-button.tsx
src/components/option/setting-random/setting-form.tsx
src/components/random-number/index.tsx

Fix button height on mobile

---

src/common/constants/index.ts
src/common/constants/setting.constant.ts
src/common/hooks/use-setting.ts
src/common/types/index.ts
src/common/types/setting.type.ts
src/common/utils/local-storage.util.ts
src/components/common/random-main/index.tsx
src/components/common/random-main/random-main-top/index.tsx
src/components/modals/modal-congrats/index.tsx
src/components/option/setting-random/custom-setting-form.tsx
src/components/option/setting-random/setting-form.tsx
src/components/random-wheel/wheel/index.tsx

[PON-82] Fix color, update storage

---

src/components/common/random-main/random-main-top/index.tsx
src/components/modals/modal-congrats-number/index.tsx
src/components/modals/modal-congrats/index.tsx
src/components/modals/modal-congrats/modal-congrats.module.scss
src/components/option/setting-button.tsx

[PON-87] Fix model UI

---

src/components/common/random-main/random-main-top/index.tsx
src/components/number-wheel/index.tsx
src/components/option/setting-button.tsx
src/components/option/setting-random/custom-setting-form.tsx
src/components/patials/header/index.tsx

[PON-89] Remove top logo, disable theme input

---

src/components/patials/header/header-left/index.tsx
src/components/patials/header/index.tsx

[PON-90] Disable header link on play

---

src/common/constants/setting.constant.ts
src/common/hooks/use-setting.ts
src/common/types/setting.type.ts
src/components/common/random-main/index.tsx
src/components/common/random-main/random-main-top/index.tsx
src/components/modals/modal-congrats-number/index.tsx
src/components/modals/modal-congrats/index.tsx
src/components/number-wheel/index.tsx
src/components/option/setting-button.tsx
src/components/option/setting-random/custom-setting-form.tsx
src/components/option/setting-random/input.tsx
src/components/option/setting-random/setting-form.tsx
src/components/random-wheel/wheel/index.tsx
src/components/timer/index.tsx
src/core-ui/color-picker-icon/index.tsx

[PON-92] Update setting UI

---

release.md

[RELEASE] 5/3/2024

---

src/common/hooks/use-setting.ts
src/common/types/setting.type.ts
src/components/number-wheel/rotation/index.tsx
src/components/setting-random/custom-setting-form.tsx

[PON-98] Add number frame switch

---

src/components/plan/payment-form.tsx
src/modules/payment/validations/payment.validator.ts

[PON-97] UI plan 2

---

release.md

[RELEASE] 07/03/2024
